# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: ":mag: COW changed preflight"
    key: cow-changed-preflight
    command: .buildkite/commands/cow-changed-preflight.sh
    plugins: [$CI_TOOLKIT_PLUGIN]
    agents:
      queue: default
    notify:
      - github_commit_status:
          context: "Buildkite / COW changed preflight"

  - label: ":crab: Linux tests (workspace, excl. CLI)"
    key: linux-tests
    command: .buildkite/commands/linux-tests.sh
    plugins:
      - $CI_TOOLKIT_PLUGIN
      - $DOCKER_PLUGIN:
          image: "$DOCKER_RUST_IMAGE"
          propagate-environment: true
          environment:
            - "CARGO_TERM_COLOR=always"
    agents:
      queue: default
    notify:
      - github_commit_status:
          context: "Buildkite / Linux tests"

  - label: ":crab: Linux build (workspace, excl. CLI)"
    key: linux-build
    depends_on: linux-tests
    command: .buildkite/commands/linux-build.sh
    plugins:
      - $CI_TOOLKIT_PLUGIN
      - $DOCKER_PLUGIN:
          image: "$DOCKER_RUST_IMAGE"
          propagate-environment: true
          environment:
            - "CARGO_TERM_COLOR=always"
    agents:
      queue: default
    notify:
      - github_commit_status:
          context: "Buildkite / Linux build"
