#!/bin/bash

# This file is `source`'d before `buildkite-agent pipeline upload` and exports
# variables that are interpolated into the pipeline YAML before upload.

CI_TOOLKIT_PLUGIN_VERSION='6.1.0'
DOCKER_PLUGIN_VERSION='v5.13.0'
RUST_IMAGE_TAG='1.85-slim-bookworm'
XCODE_VERSION=$(sed -E 's/^~> ?//' .xcode-version)

export IMAGE_ID="xcode-$XCODE_VERSION"
export CI_TOOLKIT_PLUGIN="automattic/a8c-ci-toolkit#$CI_TOOLKIT_PLUGIN_VERSION"
export DOCKER_PLUGIN="docker#$DOCKER_PLUGIN_VERSION"
export DOCKER_RUST_IMAGE="public.ecr.aws/docker/library/rust:$RUST_IMAGE_TAG"
