# frozen_string_literal: true

UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

APPLE_TEAM_ID = 'PZYM8XX95Q'

CODE_SIGNING_STORAGE_OPTIONS = {
  storage_mode: 's3',
  s3_bucket: 'a8c-fastlane-match',
  s3_region: 'us-east-2'
}.freeze

CODE_SIGNING_ENV_VARS = %w[
  MATCH_S3_ACCESS_KEY
  MATCH_S3_SECRET_ACCESS_KEY
  MATCH_PASSWORD
].freeze

ASC_API_KEY_ENV_VARS = %w[
  APP_STORE_CONNECT_API_KEY_KEY_ID
  APP_STORE_CONNECT_API_KEY_ISSUER_ID
  APP_STORE_CONNECT_API_KEY_KEY
].freeze

require 'fastlane/plugin/wpmreleasetoolkit'

EnvManager = Fastlane::Wpmreleasetoolkit::EnvManager

before_all do
  setup_ci
  EnvManager.set_up(env_file_name: 'forkpress.env')
end

desc 'Fetch the Developer ID Application certificate into the keychain'
lane :set_up_signing do |readonly: true|
  EnvManager.require_env_vars!(*CODE_SIGNING_ENV_VARS)
  EnvManager.require_env_vars!(*ASC_API_KEY_ENV_VARS) unless readonly

  sync_code_signing(
    type: 'developer_id',
    platform: 'macos',
    team_id: APPLE_TEAM_ID,
    app_identifier: [],
    api_key: readonly ? nil : app_store_connect_api_key,
    readonly: readonly,
    **CODE_SIGNING_STORAGE_OPTIONS
  )
end
